name: ADNO BUILD FULL

on:
  workflow_dispatch:

jobs:
  build:
    name: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use YARN
        uses: mskelton/setup-yarn@v1
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: yarn install
      - name: Generate build-light to create adno_light directory
        env:
          ADNO_MODE: FULL
          GRANTED_IMG_EXTENSIONS: jpg,png,JPG,PNG
          PUBLIC_URL: "/${{ github.event.repository.name }}"
        run: yarn build-full
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "adno-full/"
  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
