name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Determine APP_VERSION
        id: version
        run: |
          # Version package
          VERSION=$(jq -r .version package.json)

          # Date locale pour GitHub Actions (dd/mm/yyyy)
          BUILD_DATE=$(date +"%d/%m/%Y")

          # Déterminer APP_VERSION selon workflow / branche
          if [ "${{ github.workflow_ref }}" = *"release"* ]; then
            APP_VERSION=$VERSION
          else
            APP_VERSION="DEV (${BUILD_DATE}) ${VERSION}"
          fi

          echo "APP_VERSION=$APP_VERSION"
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Build project
        run: VITE_APP_VERSION="$APP_VERSION" npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
