name: ADNO Release & Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version à builder (ex: 1.4.2)"
        required: true
        type: string

jobs:
  build:
    name: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Determine APP_VERSION
        id: version
        run: |
          # Version package
          APP_VERSION="${{ github.event.inputs.version }}"

          echo "APP_VERSION=$APP_VERSION"
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Build for GitHub Pages
        env:
          GRANTED_IMG_EXTENSIONS: jpg,png,JPG,PNG
          PUBLIC_URL: "/${{ github.event.repository.name }}"
        run: VITE_APP_VERSION="$APP_VERSION" npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"

      - name: Build for release zip
        env:
          GRANTED_IMG_EXTENSIONS: jpg,png,JPG,PNG
          PUBLIC_URL: "./"
        run: npm run build

      - name: Zip build output
        run: zip -r adno.${{ github.event.inputs.version }}.zip dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: ADNO v${{ github.event.inputs.version }}
          files: adno.${{ github.event.inputs.version }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4